# Generated by Django 2.2.2 on 2019-11-07 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='合同名称')),
                ('contact', models.TextField(verbose_name='合同内容')),
                ('date', models.DateField(auto_now_add=True, verbose_name='合同日期')),
            ],
            options={
                'verbose_name_plural': '合同表',
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name_plural': '班级列表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name_plural': '上课记录'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name_plural': '客户跟踪记录表'},
        ),
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'verbose_name_plural': '客户信息表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学员表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name_plural': '学习记录表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '用户信息表'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='consult_courses',
            field=models.ManyToManyField(to='CRM.Course', verbose_name='咨询课程'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='紧急联系方式'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='id_card',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='jack@123.com', max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='abc123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='addr',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='学校地址'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(verbose_name='课程价格(千元)'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上课时间'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='has_homework',
            field=models.BooleanField(default=1, verbose_name='是否留有作业'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='homework',
            field=models.TextField(blank=True, verbose_name='作业需求'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='contact',
            field=models.CharField(max_length=64, unique=True, verbose_name='联系方式号码'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='contact_type',
            field=models.SmallIntegerField(choices=[(0, 'qq'), (1, '微信'), (2, '手机号')], default=0, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'QQ群'), (1, '51CTO'), (2, '百度推广'), (3, '知乎'), (4, '转介绍'), (5, '其他')], verbose_name='用户来源'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未报名'), (1, '已报名'), (2, '已退学')], verbose_name='客户跟踪状态'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=32, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CRM.CustomerInfo', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_agreed', models.BooleanField(default=False, verbose_name='合同确定状态')),
                ('contract_signed_date', models.DateTimeField(blank=True, null=True, verbose_name='合同签订日期')),
                ('contract_aproved', models.BooleanField(default=False, verbose_name='审核状态')),
                ('contract_aproved_date', models.DateTimeField(blank=True, null=True, verbose_name='审核确定日期')),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.ClassList', verbose_name='班级')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾问')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.CustomerInfo', verbose_name='签订人')),
            ],
            options={
                'unique_together': {('customer', 'class_grade')},
                'verbose_name_plural': '报名表',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_choice', models.SmallIntegerField(choices=[(0, '报名费'), (1, '学费'), (2, '退款')], verbose_name='缴费类型')),
                ('amount', models.IntegerField(default=500, verbose_name='缴费金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='缴费日期')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收费顾问')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.StudentEnrollment', verbose_name='签订合同')),
            ],
            options={
                'verbose_name_plural': '缴费记录表',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限')),
                ('url_type', models.SmallIntegerField(choices=[(0, '绝对地址'), (1, '正则地址')], default=0, verbose_name='地址书写形式')),
                ('url_name', models.CharField(default='/CRM/', max_length=128, verbose_name='地址')),
            ],
            options={
                'unique_together': {('name', 'url_name')},
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.AddField(
            model_name='classlist',
            name='contact_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.ContractTemplate', verbose_name='班级合同'),
        ),
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='CRM.Menus', verbose_name='分配权限'),
        ),
    ]
