# Generated by Django 2.2.2 on 2019-11-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20191123_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='email',
            field=models.EmailField(default='115@qq.com', max_length=254, verbose_name='个人邮箱，用作账号'),
            preserve_default=False,
        ),
    ]
