# Generated by Django 2.2.2 on 2019-11-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_studentenrollment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='email',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='个人邮箱，用作账号'),
        ),
    ]
